/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

//    a controller instance for login window it holds the shared linkedlist that has user and admin login credentails
    private LoginController controller;

    public Login() {
        initComponents();

        // creating controller so that no more controller are created inside the button clicks
        controller = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_Role = new javax.swing.ButtonGroup();
        Signup_Role = new javax.swing.ButtonGroup();
        LoginSmartPanel = new javax.swing.JPanel();
        LoginForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LoginUsernameField = new javax.swing.JTextField();
        LoginPasswordField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UserLoginConfirmBtn1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jRadio_user = new javax.swing.JRadioButton();
        jRadio_admin = new javax.swing.JRadioButton();
        Login_clear = new javax.swing.JButton();
        Signup_btn = new javax.swing.JButton();
        Signup_Form = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        SignupUsername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SignupPassword = new javax.swing.JPasswordField();
        SignupConfirmPassword = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        Signup_confirm = new javax.swing.JButton();
        BackFromSignup = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Signup_userRadio = new javax.swing.JRadioButton();
        Signup_adminRadio = new javax.swing.JRadioButton();
        Signup_clear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        Login_Role.add(jRadio_user);
        Login_Role.add(jRadio_admin);

        Signup_Role.add(Signup_userRadio);
        Signup_Role.add(Signup_adminRadio);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginSmartPanel.setLayout(new java.awt.CardLayout());

        LoginForm.setBackground(new java.awt.Color(255, 255, 255));
        LoginForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoginForm.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Login ");
        LoginForm.add(jLabel2);
        jLabel2.setBounds(310, 20, 80, 30);
        LoginForm.add(LoginUsernameField);
        LoginUsernameField.setBounds(308, 87, 132, 23);
        LoginForm.add(LoginPasswordField);
        LoginPasswordField.setBounds(308, 128, 132, 23);

        jLabel7.setText("Username:");
        LoginForm.add(jLabel7);
        jLabel7.setBounds(172, 90, 63, 17);

        jLabel8.setText("Password:");
        LoginForm.add(jLabel8);
        jLabel8.setBounds(173, 131, 62, 17);

        UserLoginConfirmBtn1.setText("Confirm");
        UserLoginConfirmBtn1.addActionListener(this::UserLoginConfirmBtn1ActionPerformed);
        LoginForm.add(UserLoginConfirmBtn1);
        UserLoginConfirmBtn1.setBounds(310, 220, 75, 23);

        jLabel13.setText("Role:");
        LoginForm.add(jLabel13);
        jLabel13.setBounds(205, 171, 30, 17);

        jRadio_user.setText("User");
        LoginForm.add(jRadio_user);
        jRadio_user.setBounds(308, 169, 50, 21);
        jRadio_user.setActionCommand("USER");
        jRadio_user.setSelected(true);

        jRadio_admin.setText("Admin");
        LoginForm.add(jRadio_admin);
        jRadio_admin.setBounds(364, 169, 60, 21);
        jRadio_admin.setActionCommand("ADMIN");

        Login_clear.setText("Clear");
        Login_clear.addActionListener(this::Login_clearActionPerformed);
        LoginForm.add(Login_clear);
        Login_clear.setBounds(410, 220, 72, 23);

        Signup_btn.setText("Signup");
        Signup_btn.addActionListener(this::Signup_btnActionPerformed);
        LoginForm.add(Signup_btn);
        Signup_btn.setBounds(310, 270, 72, 23);

        LoginSmartPanel.add(LoginForm, "login");

        Signup_Form.setBackground(new java.awt.Color(255, 255, 255));
        Signup_Form.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Signup_Form.setLayout(null);

        jLabel9.setText("Username:");
        Signup_Form.add(jLabel9);
        jLabel9.setBounds(197, 83, 63, 17);
        Signup_Form.add(SignupUsername);
        SignupUsername.setBounds(303, 80, 130, 23);

        jLabel10.setText("Password:");
        Signup_Form.add(jLabel10);
        jLabel10.setBounds(197, 115, 62, 17);

        jLabel11.setText("Confirm password:");
        Signup_Form.add(jLabel11);
        jLabel11.setBounds(150, 150, 111, 17);
        Signup_Form.add(SignupPassword);
        SignupPassword.setBounds(303, 115, 130, 23);
        Signup_Form.add(SignupConfirmPassword);
        SignupConfirmPassword.setBounds(303, 150, 130, 23);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Signup ");
        Signup_Form.add(jLabel12);
        jLabel12.setBounds(303, 27, 70, 22);

        Signup_confirm.setText("Confirm");
        Signup_confirm.addActionListener(this::Signup_confirmActionPerformed);
        Signup_Form.add(Signup_confirm);
        Signup_confirm.setBounds(300, 240, 75, 23);

        BackFromSignup.setText("Back");
        BackFromSignup.addActionListener(this::BackFromSignupActionPerformed);
        Signup_Form.add(BackFromSignup);
        BackFromSignup.setBounds(27, 29, 72, 23);

        jLabel14.setText("Role:");
        Signup_Form.add(jLabel14);
        jLabel14.setBounds(230, 190, 30, 17);

        Signup_userRadio.setText("User");
        Signup_Form.add(Signup_userRadio);
        Signup_userRadio.setBounds(303, 191, 50, 21);
        Signup_userRadio.setActionCommand("USER");
        Signup_userRadio.setSelected(true);

        Signup_adminRadio.setText("Admin");
        Signup_Form.add(Signup_adminRadio);
        Signup_adminRadio.setBounds(371, 191, 60, 21);
        Signup_adminRadio.setActionCommand("ADMIN");

        Signup_clear.setText("Clear");
        Signup_clear.addActionListener(this::Signup_clearActionPerformed);
        Signup_Form.add(Signup_clear);
        Signup_clear.setBounds(410, 240, 72, 23);

        LoginSmartPanel.add(Signup_Form, "signup");

        jLabel4.setFont(new java.awt.Font("Kannada Sangam MN", 1, 36)); // NOI18N
        jLabel4.setText("PC Hardware Vault");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LoginSmartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(LoginSmartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //this returns you back to the Login page after clicking the back button in signup form
    private void BackFromSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromSignupActionPerformed
        //opens the Login page
        controller.openLogin();
    }//GEN-LAST:event_BackFromSignupActionPerformed

//    Login Confirm button sends current login inputs to controller for validation.
//    If valid, controller opens AdminDashboard or UserView.
    private void UserLoginConfirmBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLoginConfirmBtn1ActionPerformed
        controller.login();
    }//GEN-LAST:event_UserLoginConfirmBtn1ActionPerformed

    private void Signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_btnActionPerformed
//     opens the signup form for both user and admin with the option to choose role 
        controller.openSignup();
    }//GEN-LAST:event_Signup_btnActionPerformed

//    Signup Confirm button sends signup inputs (username, pass, confirm pass, role)
//    to controller, which creates account in the LinkedList and shows success/error
    private void Signup_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_confirmActionPerformed
        controller.signup();
    }//GEN-LAST:event_Signup_confirmActionPerformed

    private void Signup_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_clearActionPerformed
        //clears the signup form
        clearSignupForm();
    }//GEN-LAST:event_Signup_clearActionPerformed

    private void Login_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_clearActionPerformed
        // clears the login form
        clearLoginForm();
    }//GEN-LAST:event_Login_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackFromSignup;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JPasswordField LoginPasswordField;
    private javax.swing.JPanel LoginSmartPanel;
    private javax.swing.JTextField LoginUsernameField;
    private javax.swing.ButtonGroup Login_Role;
    private javax.swing.JButton Login_clear;
    private javax.swing.JPasswordField SignupConfirmPassword;
    private javax.swing.JPasswordField SignupPassword;
    private javax.swing.JTextField SignupUsername;
    private javax.swing.JPanel Signup_Form;
    private javax.swing.ButtonGroup Signup_Role;
    private javax.swing.JRadioButton Signup_adminRadio;
    private javax.swing.JButton Signup_btn;
    private javax.swing.JButton Signup_clear;
    private javax.swing.JButton Signup_confirm;
    private javax.swing.JRadioButton Signup_userRadio;
    private javax.swing.JButton UserLoginConfirmBtn1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadio_admin;
    private javax.swing.JRadioButton jRadio_user;
    // End of variables declaration//GEN-END:variables

    // Card names must match exactly the names used in:
    // LoginSmartPanel.add(LoginForm, "card2");
    // LoginSmartPanel.add(Signup_Form, "card4");
    private static final String CARD_LOGIN = "login";
    private static final String CARD_SIGNUP = "signup";

    //this method returns the cardname 
    public void showCard(String cardName) {
        java.awt.CardLayout cl = (java.awt.CardLayout) LoginSmartPanel.getLayout();
        cl.show(LoginSmartPanel, cardName);
    }

    //getter methods for the Login page
    //the getSelectedRole method returns the selected role from the loginform and validated if the selection is null 
    public String getSelectedRole() {
        if (Login_Role.getSelection() == null) {
            return null;
        }
        return Login_Role.getSelection().getActionCommand(); // get selected role 
    }

    //this method returns the username from the login form
    public String getUsername() {
        return LoginUsernameField.getText();
    }

    //this method returns the password from the login form
    public String getPassword() {
        return new String(LoginPasswordField.getPassword());
    }

//    getter methods for the signup page
    //this method returns the selected role from the signup form and also validates if the role is selected or not 
    public String getSignupRole() {
        if (Signup_Role.getSelection() == null) {
            return null;
        }
        return Signup_Role.getSelection().getActionCommand();
    }

    //this method returns the username that is given in the signup form
    public String getSignupUsername() {
        return SignupUsername.getText();
    }

    //this method returns the password that is given in the singup form
    public String getSignupPassword() {
        return new String(SignupPassword.getPassword());
    }

    // this method returns the confirm password from the signupform 
    public String getSignupConfirmPassword() {
        return new String(SignupConfirmPassword.getPassword());
    }

    //Shows an error message dialog (used for validation errors and invalid login)
    public void showError(String msg) {
        javax.swing.JOptionPane.showMessageDialog(
                this, msg, "Error", javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }

    //Shows an information message dialog (used for success messages).
    public void showInfo(String msg) {
        javax.swing.JOptionPane.showMessageDialog(
                this, msg, "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }

    //Clears the login form inputs and resets role selection to default User.
    public void clearLoginForm() {
        LoginUsernameField.setText("");
        LoginPasswordField.setText("");
        Login_Role.clearSelection();
        jRadio_user.setSelected(true); // optional default
    }

    //Clears the signup form inputs and resets role selection to default User.
    public void clearSignupForm() {
        SignupUsername.setText("");
        SignupPassword.setText("");
        SignupConfirmPassword.setText("");
        Signup_Role.clearSelection();
        Signup_userRadio.setSelected(true); // optional default
    }

}
