/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CartController;
import Model.CartItem;
import Model.CartStack;
import Controller.PCComponentController;
import Model.PCComponent;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import Model.PCComponentTableModel;
import java.awt.Image;
import java.net.URL;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sonamchhiringsherpa
 */
public class UserView extends javax.swing.JFrame {

    private final CartStack cartStack = new CartStack();
    private final CartController cartController = new CartController(cartStack);

    private final PCComponentTableModel tableModel = new PCComponentTableModel(120, 80);
    private final TableRowSorter<PCComponentTableModel> sorter = new TableRowSorter<>(tableModel);

    LinkedList<PCComponent> components = PCComponent.getComponents();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserView.class.getName());

    /**
     * Creates new form UserView
     */
    public UserView() {
        initComponents();

        componentTable.setModel(tableModel);
        componentTable.setRowSorter(sorter);   // sorting/filtering support [web:418]
        componentTable.setRowHeight(130);

        // cart table (image + row height)
        setupCartTableModel();
        jTable1.setRowHeight(130);
        PCComponent.initDummyData();
        refreshTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JButton();
        NavigationPanel = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        Components = new javax.swing.JButton();
        Cart = new javax.swing.JButton();
        SmartPanel = new javax.swing.JPanel();
        AboutUsPanel = new javax.swing.JPanel();
        ComponentsPanel = new javax.swing.JPanel();
        FilterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        componentList_combobox = new javax.swing.JComboBox<>();
        sortByName = new javax.swing.JButton();
        sortByPrice = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        filterBtn = new javax.swing.JButton();
        ItemPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        componentTable = new javax.swing.JTable();
        addToCart = new javax.swing.JButton();
        CartPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        updateCartQuantity = new javax.swing.JButton();
        placeOrder = new javax.swing.JButton();
        HomePanel = new javax.swing.JPanel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PC Component Management System");

        LogOutButton.setText("LogOut");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        NavigationPanel.setBackground(new java.awt.Color(204, 204, 204));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        AboutUs.setText("AboutUs");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });

        Components.setText("Components");
        Components.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComponentsActionPerformed(evt);
            }
        });

        Cart.setText("Cart");
        Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigationPanelLayout = new javax.swing.GroupLayout(NavigationPanel);
        NavigationPanel.setLayout(NavigationPanelLayout);
        NavigationPanelLayout.setHorizontalGroup(
            NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AboutUs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addComponent(Components, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addComponent(Cart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );
        NavigationPanelLayout.setVerticalGroup(
            NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Components, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
        );

        SmartPanel.setBackground(new java.awt.Color(255, 255, 255));
        SmartPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SmartPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout AboutUsPanelLayout = new javax.swing.GroupLayout(AboutUsPanel);
        AboutUsPanel.setLayout(AboutUsPanelLayout);
        AboutUsPanelLayout.setHorizontalGroup(
            AboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        AboutUsPanelLayout.setVerticalGroup(
            AboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        SmartPanel.add(AboutUsPanel, "card3");

        FilterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Filters:");

        jLabel3.setText("Component Type:");

        componentList_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","CPU","GPU","Motherboard","RAM","PSU" }));

        sortByName.setText("Sort By Name");
        sortByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByNameActionPerformed(evt);
            }
        });

        sortByPrice.setText("Sort By Price");
        sortByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByPriceActionPerformed(evt);
            }
        });

        searchField.setText("Search");
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        filterBtn.setText("Filter");
        filterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FilterPanelLayout = new javax.swing.GroupLayout(FilterPanel);
        FilterPanel.setLayout(FilterPanelLayout);
        FilterPanelLayout.setHorizontalGroup(
            FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FilterPanelLayout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FilterPanelLayout.createSequentialGroup()
                        .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FilterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(componentList_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(filterBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE))
                            .addGroup(FilterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sortByName)))
                        .addGap(18, 18, 18)
                        .addComponent(sortByPrice)
                        .addGap(94, 94, 94))))
        );
        FilterPanelLayout.setVerticalGroup(
            FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPanelLayout.createSequentialGroup()
                .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FilterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(componentList_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filterBtn)))
                    .addGroup(FilterPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sortByName)
                            .addComponent(sortByPrice))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        ItemPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        componentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Component Type", "Status", "Quantity", "Price", "Image"
            }
        ));
        jScrollPane1.setViewportView(componentTable);

        javax.swing.GroupLayout ItemPanelLayout = new javax.swing.GroupLayout(ItemPanel);
        ItemPanel.setLayout(ItemPanelLayout);
        ItemPanelLayout.setHorizontalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        ItemPanelLayout.setVerticalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );

        addToCart.setText("Add to Cart");
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ComponentsPanelLayout = new javax.swing.GroupLayout(ComponentsPanel);
        ComponentsPanel.setLayout(ComponentsPanelLayout);
        ComponentsPanelLayout.setHorizontalGroup(
            ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComponentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FilterPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ComponentsPanelLayout.createSequentialGroup()
                        .addComponent(addToCart)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ComponentsPanelLayout.setVerticalGroup(
            ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComponentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(addToCart)
                .addGap(86, 86, 86))
        );

        SmartPanel.add(ComponentsPanel, "card4");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Image", "Name", "Component Type", "Quantity", "Unit Price", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Your Items");

        updateCartQuantity.setText("Update Qty");
        updateCartQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCartQuantityActionPerformed(evt);
            }
        });

        placeOrder.setText("Place Order");

        javax.swing.GroupLayout CartPanelLayout = new javax.swing.GroupLayout(CartPanel);
        CartPanel.setLayout(CartPanelLayout);
        CartPanelLayout.setHorizontalGroup(
            CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                    .addGroup(CartPanelLayout.createSequentialGroup()
                        .addGroup(CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(CartPanelLayout.createSequentialGroup()
                                .addComponent(updateCartQuantity)
                                .addGap(28, 28, 28)
                                .addComponent(placeOrder)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CartPanelLayout.setVerticalGroup(
            CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(CartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCartQuantity)
                    .addComponent(placeOrder))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        SmartPanel.add(CartPanel, "card5");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        SmartPanel.add(HomePanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SmartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SmartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComponentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComponentsActionPerformed
        // TODO add your handling code here:
        SmartPanel.removeAll();
        SmartPanel.add(ComponentsPanel);
        SmartPanel.repaint();
        SmartPanel.revalidate();

    }//GEN-LAST:event_ComponentsActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        SmartPanel.removeAll();
        SmartPanel.add(HomePanel);
        SmartPanel.repaint();
        SmartPanel.revalidate();
    }//GEN-LAST:event_HomeActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        // TODO add your handling code here:
        SmartPanel.removeAll();
        SmartPanel.add(AboutUsPanel);
        SmartPanel.repaint();
        SmartPanel.revalidate();
    }//GEN-LAST:event_AboutUsActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed

        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);

        // Close current UserView JFrame
        this.setVisible(false);

    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void sortByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByNameActionPerformed
        LinkedList<PCComponent> sorted = controller.sortByName();
        tableModel.setData(sorted);
    }//GEN-LAST:event_sortByNameActionPerformed

    private void sortByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByPriceActionPerformed
        LinkedList<PCComponent> sorted = controller.sortByPrice();
        tableModel.setData(sorted);
    }//GEN-LAST:event_sortByPriceActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchTerm = searchField.getText().trim();
        if (searchTerm.isEmpty() || searchTerm.equals("Search")) {
            JOptionPane.showMessageDialog(this, "Please enter a search term.", "Search Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LinkedList<PCComponent> results = controller.searchByName(searchTerm);
        tableModel.setData(results);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void filterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBtnActionPerformed
        String type = (String) componentList_combobox.getSelectedItem();
        if (type == null || type.isEmpty() || componentList_combobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a valid component type.", "Filter Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LinkedList<PCComponent> filtered = controller.filterByType(type);
        tableModel.setData(filtered);
    }//GEN-LAST:event_filterBtnActionPerformed

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
        searchField.setText("");
    }//GEN-LAST:event_searchFieldMouseClicked

    private void CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartActionPerformed
        SmartPanel.removeAll();
        SmartPanel.add(CartPanel);
        SmartPanel.repaint();
        SmartPanel.revalidate();
    }//GEN-LAST:event_CartActionPerformed

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
        // TODO add your handling code here:
        int viewRow = componentTable.getSelectedRow();
    if (viewRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product first.");
        return;
    }

    int modelRow = componentTable.convertRowIndexToModel(viewRow);
    PCComponent selected = tableModel.getComponentAt(modelRow);

    if (selected == null) {
        JOptionPane.showMessageDialog(this, "Invalid selection.");
        return;
    }

    // dialog (view job)
    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

    String desc =
            "Name: " + selected.getName() + "\n"
            + "Type: " + selected.getType() + "\n"
            + "Status: " + selected.getStatus() + "\n"
            + "Available Qty: " + selected.getQuantity() + "\n"
            + "Price: " + selected.getPrice();

    panel.add(new JLabel("<html>" + desc.replace("\n", "<br>") + "</html>"));
    panel.add(new JLabel(" "));

    int maxQty = selected.getQuantity();
    if (maxQty <= 0) {
        JOptionPane.showMessageDialog(this, "This product is out of stock.");
        return;
    }

    SpinnerNumberModel model = new SpinnerNumberModel(1, 1, maxQty, 1);
    JSpinner spinner = new JSpinner(model);

    JPanel qtyPanel = new JPanel();
    qtyPanel.add(new JLabel("Quantity: "));
    qtyPanel.add(spinner);
    panel.add(qtyPanel);

    int option = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Add to Cart",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.INFORMATION_MESSAGE
    );

    if (option != JOptionPane.OK_OPTION) return;

    int qty = ((Integer) spinner.getValue()).intValue();

    try {
        cartController.addToCart(selected, qty);   // controller updates stock/status + pushes to stack
        refreshTable();
        refreshCartTable();
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }


    }//GEN-LAST:event_addToCartActionPerformed

    private void updateCartQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCartQuantityActionPerformed
        // TODO add your handling code here:
        
   
    int cartRow = jTable1.getSelectedRow();
    if (cartRow == -1) {
        JOptionPane.showMessageDialog(this, "Select an item in the cart first.");
        return;
    }

    CartItem item = cartStack.getAt(cartRow);
    if (item == null) {
        JOptionPane.showMessageDialog(this, "Invalid cart selection.");
        return;
    }

    PCComponent pc = item.getComponent();
    int oldQty = item.getQuantity();

    int maxAllowed = pc.getQuantity() + oldQty;
    if (maxAllowed <= 0) {
        JOptionPane.showMessageDialog(this, "This product is out of stock.");
        return;
    }

    JSpinner spinner = new JSpinner(new SpinnerNumberModel(oldQty, 1, maxAllowed, 1));

    int option = JOptionPane.showConfirmDialog(
            this,
            spinner,
            "Update quantity (max " + maxAllowed + ")",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (option != JOptionPane.OK_OPTION) return;

    int newQty = ((Integer) spinner.getValue()).intValue();

    try {
        cartController.updateCartQuantityAt(cartRow, newQty);
        refreshTable();
        refreshCartTable();
    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }//GEN-LAST:event_updateCartQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserView().setVisible(true));
    }
    private PCComponentController controller = new PCComponentController();
    
    private void setupCartTableModel() {
    jTable1.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"Image", "Name", "Component Type", "Quantity", "Unit Price", "Total"}
    ) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (columnIndex == 0) {
                return Icon.class; // Image column [web:175][web:406]
            }
            return Object.class;
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    });
}


  private void refreshTable() {
    tableModel.setData(PCComponent.getComponents());
}


   private void refreshCartTable() {

    DefaultTableModel cartModel = (DefaultTableModel) jTable1.getModel();
    cartModel.setRowCount(0);

    java.util.List<CartItem> items = cartStack.toList();

    for (int i = 0; i < items.size(); i++) {
        CartItem ci = items.get(i);
        PCComponent pc = ci.getComponent();

        ImageIcon cartThumb = makeCartThumbnail(pc.getImagePath(), 120, 120);

        cartModel.addRow(new Object[]{
            cartThumb,
            pc.getName(),
            pc.getType(),
            ci.getQuantity(),
            pc.getPrice(),
            ci.getTotalPrice()
        });
    }
}
   private ImageIcon makeCartThumbnail(String imagePath, int w, int h) {
    if (imagePath == null || imagePath.trim().isEmpty()) return null;

    ImageIcon icon = null;

    // resource path (predefined): "/images/x.png"
    if (imagePath.startsWith("/")) {
        URL url = getClass().getResource(imagePath);
        if (url != null) {
            icon = new ImageIcon(url);
        }
    } else {
        // file path (chosen by user)
        icon = new ImageIcon(imagePath);
    }

    if (icon == null) return null;

    Image img = icon.getImage();
    Image scaled = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
    return new ImageIcon(scaled);
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JPanel AboutUsPanel;
    private javax.swing.JButton Cart;
    private javax.swing.JPanel CartPanel;
    private javax.swing.JButton Components;
    private javax.swing.JPanel ComponentsPanel;
    private javax.swing.JPanel FilterPanel;
    private javax.swing.JButton Home;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel ItemPanel;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JPanel NavigationPanel;
    private javax.swing.JPanel SmartPanel;
    private javax.swing.JButton addToCart;
    private javax.swing.JComboBox<String> componentList_combobox;
    private javax.swing.JTable componentTable;
    private javax.swing.JButton filterBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton placeOrder;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton sortByName;
    private javax.swing.JButton sortByPrice;
    private javax.swing.JButton updateCartQuantity;
    // End of variables declaration//GEN-END:variables

}
