/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.UserController;
import Model.CartTableModel;
import Model.Inventory;
import Model.PCComponent;
import Model.ProductTableModel;

/**
 *
 * @author sonamchhiringsherpa
 */
public class User extends javax.swing.JFrame {

    // Controller (logic)
    private final UserController controller = new UserController();

// Table models (UI data models)
    private final ProductTableModel productModel = new ProductTableModel(240, 160);

    private CartTableModel cartModel; // created after controller cart exists
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User.class.getName());

    private final Model.UserOrderTableModel userOrderModel = new Model.UserOrderTableModel();

    private final Model.OrderDetailTableModel orderDetailModel = new Model.OrderDetailTableModel(80, 80);

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        OrderTable.setModel(userOrderModel);         // Orders table (left)
        ProductTable1.setModel(orderDetailModel); // Order Detail table (right)
        // Order Detail table (right side) sizing
        ProductTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);

// Keep image column fixed width
        ProductTable1.getColumnModel().getColumn(0).setMinWidth(120);
        ProductTable1.getColumnModel().getColumn(0).setPreferredWidth(120);
        ProductTable1.getColumnModel().getColumn(0).setMaxWidth(120);

        ProductTable1.setRowHeight(90);// must be >= your OrderDetailTableModel thumbH (80)
        ProductTable1.getColumnModel().getColumn(0).setPreferredWidth(120); // image column

        // Make sure dummy inventory exists
        Inventory.initDummyDataIfEmpty();

        // PRODUCT TABLE SETUP
        ProductTable.setModel(productModel);

// row height should be >= thumbnail height
        ProductTable.setRowHeight(180);

// make image column wider
        ProductTable.getColumnModel().getColumn(5).setPreferredWidth(300);

        productModel.setData(controller.getInventory());

        // CART TABLE SETUP
        cartModel = new CartTableModel(controller.getCart(), 80, 80);
        CartTable.setModel(cartModel);
        CartTable.setRowHeight(100);

        // (Optional) default placeholder text behavior
        searchField.setText("Search");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ProductPanel = new javax.swing.JPanel();
        FilterPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        componentList_combobox = new javax.swing.JComboBox<>();
        sortByName = new javax.swing.JButton();
        sortByPrice = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        filterBtn = new javax.swing.JButton();
        addToCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        CartPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CartTable = new javax.swing.JTable();
        updateCartOrder = new javax.swing.JButton();
        OrderBtn1 = new javax.swing.JButton();
        OrderPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        ViewOrderDetails = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ProductTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Kannada Sangam MN", 1, 36)); // NOI18N
        jLabel2.setText("PC Hardware Vault");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 30, 590, 59);

        LogoutBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LogoutBtn);
        LogoutBtn.setBounds(1160, 30, 90, 50);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        ProductPanel.setBackground(new java.awt.Color(255, 255, 255));
        ProductPanel.setLayout(null);

        FilterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Filters:");

        jLabel4.setText("Component Type:");

        componentList_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","CPU","GPU","Motherboard","RAM","PSU" }));

        sortByName.setText("Sort By Name");
        sortByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByNameActionPerformed(evt);
            }
        });

        sortByPrice.setText("Sort By Price");
        sortByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByPriceActionPerformed(evt);
            }
        });

        searchField.setText("Search");
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        filterBtn.setText("Filter");
        filterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FilterPanelLayout = new javax.swing.GroupLayout(FilterPanel);
        FilterPanel.setLayout(FilterPanelLayout);
        FilterPanelLayout.setHorizontalGroup(
            FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FilterPanelLayout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FilterPanelLayout.createSequentialGroup()
                        .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FilterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(componentList_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(filterBtn)
                                .addGap(107, 107, 107)
                                .addComponent(sortByName)
                                .addGap(18, 18, 18)
                                .addComponent(sortByPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE))
                            .addGroup(FilterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(218, 218, 218))))
        );
        FilterPanelLayout.setVerticalGroup(
            FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(componentList_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterBtn)
                    .addComponent(sortByName)
                    .addComponent(sortByPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        ProductPanel.add(FilterPanel);
        FilterPanel.setBounds(20, 10, 1040, 93);

        addToCart.setText("Add to Cart");
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });
        ProductPanel.add(addToCart);
        addToCart.setBounds(1080, 100, 120, 40);

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Component Type", "Status", "Quantity", "Price", "Image"
            }
        ));
        jScrollPane1.setViewportView(ProductTable);

        ProductPanel.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 1040, 590);

        jTabbedPane1.addTab("Product", ProductPanel);

        CartPanel.setBackground(new java.awt.Color(255, 255, 255));
        CartPanel.setLayout(null);

        CartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Image", "Name", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane2.setViewportView(CartTable);

        CartPanel.add(jScrollPane2);
        jScrollPane2.setBounds(10, 40, 1040, 550);

        updateCartOrder.setText("Update Order");
        updateCartOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCartOrderActionPerformed(evt);
            }
        });
        CartPanel.add(updateCartOrder);
        updateCartOrder.setBounds(1080, 100, 150, 40);

        OrderBtn1.setText("Order");
        OrderBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBtn1ActionPerformed(evt);
            }
        });
        CartPanel.add(OrderBtn1);
        OrderBtn1.setBounds(1080, 40, 150, 40);

        jTabbedPane1.addTab("Cart", CartPanel);

        OrderPanel.setBackground(new java.awt.Color(255, 255, 255));
        OrderPanel.setLayout(null);

        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "OrderId", "Date", "Location", "Status", "Total Amount"
            }
        ));
        jScrollPane3.setViewportView(OrderTable);

        OrderPanel.add(jScrollPane3);
        jScrollPane3.setBounds(10, 50, 680, 290);

        ViewOrderDetails.setText("View Order Detail");
        ViewOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrderDetailsActionPerformed(evt);
            }
        });
        OrderPanel.add(ViewOrderDetails);
        ViewOrderDetails.setBounds(30, 370, 140, 40);

        ProductTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Image", "Name", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane4.setViewportView(ProductTable1);

        OrderPanel.add(jScrollPane4);
        jScrollPane4.setBounds(700, 50, 620, 530);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Order Detial");
        OrderPanel.add(jLabel1);
        jLabel1.setBounds(710, 20, 90, 18);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Orders");
        OrderPanel.add(jLabel5);
        jLabel5.setBounds(20, 20, 60, 18);

        jTabbedPane1.addTab("Orders", OrderPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByNameActionPerformed
// Sort by name and refresh table with sorted copy
        productModel.setData(controller.sortByName());
    }//GEN-LAST:event_sortByNameActionPerformed

    private void sortByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByPriceActionPerformed
        // Sort by price and refresh table with sorted copy
        productModel.setData(controller.sortByPrice());
    }//GEN-LAST:event_sortByPriceActionPerformed

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
        // Clear placeholder text only once
        if ("Search".equals(searchField.getText())) {
            searchField.setText("");
        }
    }//GEN-LAST:event_searchFieldMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String text = searchField.getText();

        // If empty -> show all products
        if (text == null || text.trim().isEmpty() || "Search".equalsIgnoreCase(text.trim())) {
            productModel.setData(controller.getInventory());
            return;
        }

        // Linear search and update table with results
        java.util.LinkedList<PCComponent> results = controller.searchByNameLinear(text);

        if (results.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No matching products found.");
            productModel.setData(controller.getInventory());
            return;
        }

        productModel.setData(results);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void filterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBtnActionPerformed
// Filter table by selected component type
        String type = componentList_combobox.getSelectedItem().toString();
        productModel.setData(controller.filterByType(type));
    }//GEN-LAST:event_filterBtnActionPerformed

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
        int viewRow = ProductTable.getSelectedRow();
        if (viewRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a product first.");
            return;
        }

        int modelRow = ProductTable.convertRowIndexToModel(viewRow);

        PCComponent selected = productModel.getAt(modelRow);

// limit quantity by available stock
        int maxQty = selected.getQuantity();
        if (maxQty <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Out of stock!");
            return;
        }

// Description text (adjust to what you have; if no description, show name/type/price)
        String desc = "Name: " + selected.getName()
                + "\nType: " + selected.getType()
                + "\nPrice: " + selected.getPrice()
                + "\nAvailable: " + selected.getQuantity();

        javax.swing.JSpinner spinner = new javax.swing.JSpinner(
                new javax.swing.SpinnerNumberModel(1, 1, maxQty, 1)
        );

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(10, 10));
        panel.add(new javax.swing.JLabel("<html>" + desc.replace("\n", "<br>") + "</html>"),
                java.awt.BorderLayout.CENTER);

        javax.swing.JPanel qtyPanel = new javax.swing.JPanel();
        qtyPanel.add(new javax.swing.JLabel("Quantity: "));
        qtyPanel.add(spinner);
        panel.add(qtyPanel, java.awt.BorderLayout.SOUTH);

        int result = javax.swing.JOptionPane.showConfirmDialog(
                this, panel, "Add to cart",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.PLAIN_MESSAGE
        );

        if (result != javax.swing.JOptionPane.OK_OPTION) {
            return;
        }

        int qty = (Integer) spinner.getValue();

// Do the real update in controller
        boolean ok = controller.addToCartAndDecreaseStock(selected, qty);

        if (!ok) {
            javax.swing.JOptionPane.showMessageDialog(this, "Not enough stock!");
            return;
        }

// refresh both tables
        cartModel.refresh();
        productModel.fireTableDataChanged();

    }//GEN-LAST:event_addToCartActionPerformed

    private void updateCartOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCartOrderActionPerformed
        int row = CartTable.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a cart item first.");
            return;
        }

        int modelRow = CartTable.convertRowIndexToModel(row);

        // Read current values from CartTableModel
        Model.CartItem item = controller.getCart().getAt(modelRow);
        Model.PCComponent p = item.getProduct();

        int oldQty = item.getQty();

        // Max allowed = current cart qty + inventory qty
        int maxQty = oldQty + p.getQuantity();

        String desc = "Name: " + p.getName()
                + "\nType: " + p.getType()
                + "\nPrice: " + p.getPrice()
                + "\nIn inventory: " + p.getQuantity()
                + "\nIn cart: " + oldQty;

        javax.swing.JSpinner spinner = new javax.swing.JSpinner(
                new javax.swing.SpinnerNumberModel(oldQty, 0, maxQty, 1)
        );

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(10, 10));
        panel.add(new javax.swing.JLabel("<html>" + desc.replace("\n", "<br>") + "</html>"),
                java.awt.BorderLayout.CENTER);

        javax.swing.JPanel qtyPanel = new javax.swing.JPanel();
        qtyPanel.add(new javax.swing.JLabel("New quantity: "));
        qtyPanel.add(spinner);
        panel.add(qtyPanel, java.awt.BorderLayout.SOUTH);

        int result = javax.swing.JOptionPane.showConfirmDialog(
                this, panel, "Update cart item",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.PLAIN_MESSAGE
        );

        if (result != javax.swing.JOptionPane.OK_OPTION) {
            return;
        }

        int newQty = (Integer) spinner.getValue();

        boolean ok = controller.updateCartItemQty(modelRow, newQty);
        if (!ok) {
            javax.swing.JOptionPane.showMessageDialog(this, "Not enough stock to increase quantity.");
            return;
        }

        // Refresh tables
        cartModel.refresh();
        productModel.fireTableDataChanged();
    }//GEN-LAST:event_updateCartOrderActionPerformed

    private void ViewOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOrderDetailsActionPerformed
        int viewRow = OrderTable.getSelectedRow();
        if (viewRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select an order first.");
            return;
        }

        int modelRow = OrderTable.convertRowIndexToModel(viewRow);

        Model.Order o = userOrderModel.getOrderAtRow(modelRow);
        if (o == null) {
            return;
        }

        orderDetailModel.setItems(o.getItems());
    }//GEN-LAST:event_ViewOrderDetailsActionPerformed

    private void OrderBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBtn1ActionPerformed
        javax.swing.JTextField locationField = new javax.swing.JTextField(25);

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(10, 10));
        panel.add(new javax.swing.JLabel("Enter delivery location:"), java.awt.BorderLayout.NORTH);
        panel.add(locationField, java.awt.BorderLayout.CENTER);

        int result = javax.swing.JOptionPane.showConfirmDialog(
                this,
                panel,
                "Place Order",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.PLAIN_MESSAGE
        ); // dialog input [web:257]

        if (result != javax.swing.JOptionPane.OK_OPTION) {
            return;
        }

        String location = locationField.getText();

        Model.Order created = controller.placeOrder(location);
        if (created == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cart is empty or location is invalid.");
            return;
        }

        String msg = "OrderId: " + created.getOrderId()
                + "\nDate: " + created.getDate()
                + "\nLocation: " + created.getLocation()
                + "\nTotal Amount: " + created.getTotalAmount();

        javax.swing.JOptionPane.showMessageDialog(this, msg);

        // Refresh tables
        userOrderModel.refresh();
        cartModel.refresh();             // cart cleared
        orderDetailModel.setItems(null); // clear right table until user selects an order
    }//GEN-LAST:event_OrderBtn1ActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        Model.UserSession.logout(); // does NOT delete carts from repository
        this.dispose();
        new View.Login().setVisible(true);
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        int index = jTabbedPane1.getSelectedIndex();
        String title = jTabbedPane1.getTitleAt(index);
        if ("Orders".equals(title)) {
            userOrderModel.refresh(); // inside, call fireTableDataChanged()
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new User().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CartPanel;
    private javax.swing.JTable CartTable;
    private javax.swing.JPanel FilterPanel;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton OrderBtn1;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JTable OrderTable;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JTable ProductTable;
    private javax.swing.JTable ProductTable1;
    private javax.swing.JButton ViewOrderDetails;
    private javax.swing.JButton addToCart;
    private javax.swing.JComboBox<String> componentList_combobox;
    private javax.swing.JButton filterBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton sortByName;
    private javax.swing.JButton sortByPrice;
    private javax.swing.JButton updateCartOrder;
    // End of variables declaration//GEN-END:variables
}
